import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>FORZA UI</title>
        {/* <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Assistant:wght@200..800&family=Cabin:ital,wght@0,400..700;1,400..700&display=swap" rel="stylesheet" /> */}
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
